import type { Metadata } from "next";
import { Montserrat, Roboto_Condensed } from "next/font/google";
import "../../app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ChatBubble from "@/components/ChatBubble";
import { UserProvider } from "@/context/UserContext";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const roboto = Roboto_Condensed({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Cameras, Lenses, Camcorders & Printers - Canon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar />
      <body className={`${roboto.variable}${montserrat.variable} antialiased`}>
        <UserProvider>{children}</UserProvider>
      </body>
      <ChatBubble />
      <Footer />
    </html>
  );
}
