import type { Metadata } from "next";
import { Montserrat, Roboto_Condensed } from "next/font/google";
import "../../app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ChatBubble from "@/components/ChatBubble";
import { UserProvider } from "@/context/UserContext";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "sonner";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const roboto = Roboto_Condensed({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Cameras, Lenses, Camcorders & Printers - Canon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //1a2746
    <html lang="en">
      <body className={`${roboto.variable}${montserrat.variable}  antialiased`}>
        <UserProvider>
          <CartProvider>
            <>
              <Toaster
                position="top-center"
                expand
                richColors
                closeButton
                offset={16}
                toastOptions={{
                  style: {
                    justifyContent: "center",
                    gap: 2,
                    background: "#cfd6e8",
                  },
                }}
              />
              <Navbar />

              {children}
              <ChatBubble />
              <Footer />
            </>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
