import type { Metadata } from "next";
import "../../src/app/globals.css";
import { UserProvider } from "@/context/UserContext";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Digital Cameras, Lenses, Camcorders & Printers - Canon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <UserProvider>
          <>
            <Toaster
              position="top-center"
              expand
              richColors
              closeButton
              offset={16}
              toastOptions={{
                style: {
                  justifyContent: "center",
                  gap: 2,
                  background: "#cfd6e8",
                },
              }}
            />
            {children}
          </>
        </UserProvider>
      </body>
    </html>
  );
}
