import type { Metadata } from "next";
import "../../src/app/globals.css";
import { UserProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Digital Cameras, Lenses, Camcorders & Printers - Canon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
